name: Docker Image Build
on:
  workflow_dispatch:
  release:
    types: [created]

jobs:
  publish_images:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: build image
        run: |
          docker build ./docker/ -t ${{ secrets.DOCKERHUB_USERNAME }}/tumblr-uploader:${{ github.event.release.name }} -t ${{ secrets.DOCKERHUB_USERNAME }}/tumblr-uploader:latest
          docker build ./auth/ -t ${{ secrets.DOCKERHUB_USERNAME }}/tumblr-oauth:${{ github.event.release.name }} -t ${{ secrets.DOCKERHUB_USERNAME }}/tumblr-oauth:latest
      - name: push image to docker hub
        run: |
          docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/tumblr-uploader:${{ github.event.release.name }}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/tumblr-uploader:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/tumblr-oauth:${{ github.event.release.name }}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/tumblr-oauth:latest


